/**
 * Từ điển mặc định: thuật ngữ y khoa hay xuất hiện trong giao ban (ưu tiên Gây mê hồi sức).
 * `aliases` là cách phát âm/nghe nhầm thường gặp — giúp mô hình viết đúng chính tả chuẩn.
 * Người dùng/nhóm/quản trị có thể bổ sung thêm trong mục "Từ điển".
 */
export interface GlossaryEntry {
  term: string;
  aliases?: string[];
  category?: string;
}

export const DEFAULT_GLOSSARY: GlossaryEntry[] = [
  // Thuốc mê, giảm đau, giãn cơ, hồi sức
  { term: "Propofol", aliases: ["prô pô phôn"], category: "thuốc" },
  { term: "Fentanyl", aliases: ["phen ta nin"], category: "thuốc" },
  { term: "Sufentanil", category: "thuốc" },
  { term: "Remifentanil", category: "thuốc" },
  { term: "Morphin", category: "thuốc" },
  { term: "Ketamine", aliases: ["kê ta min"], category: "thuốc" },
  { term: "Etomidate", category: "thuốc" },
  { term: "Midazolam", category: "thuốc" },
  { term: "Sevoflurane", aliases: ["sevo", "sê vô"], category: "thuốc" },
  { term: "Desflurane", category: "thuốc" },
  { term: "Isoflurane", category: "thuốc" },
  { term: "Esmeron", aliases: ["ét mê rôn", "ếch mê rông"], category: "thuốc" },
  { term: "Rocuronium", category: "thuốc" },
  { term: "Suxamethonium", aliases: ["sux", "xúc xa mê tô ni um"], category: "thuốc" },
  { term: "Atracurium", category: "thuốc" },
  { term: "Cisatracurium", category: "thuốc" },
  { term: "Neostigmine", category: "thuốc" },
  { term: "Sugammadex", aliases: ["Bridion", "su ga ma đéc"], category: "thuốc" },
  { term: "Atropin", category: "thuốc" },
  { term: "Ephedrine", aliases: ["ê phê đrin"], category: "thuốc" },
  { term: "Noradrenaline", aliases: ["nô ra đrê na lin", "nor"], category: "thuốc" },
  { term: "Adrenaline", category: "thuốc" },
  { term: "Phenylephrine", category: "thuốc" },
  { term: "Dobutamine", category: "thuốc" },
  { term: "Dopamine", category: "thuốc" },
  { term: "Axit Tranexamic", aliases: ["transamin", "tranexamic acid"], category: "thuốc" },
  { term: "Paracetamol", category: "thuốc" },
  { term: "Nefopam", category: "thuốc" },
  { term: "Celecoxib", category: "thuốc" },
  { term: "Ketorolac", category: "thuốc" },
  { term: "Bupivacaine", aliases: ["Marcaine", "bu pi va cain"], category: "thuốc" },
  { term: "Levobupivacaine", category: "thuốc" },
  { term: "Lidocaine", category: "thuốc" },
  { term: "Ondansetron", category: "thuốc" },
  { term: "Dexamethasone", category: "thuốc" },
  { term: "Heparin", category: "thuốc" },
  { term: "Enoxaparin", aliases: ["Lovenox"], category: "thuốc" },
  { term: "Amlor", aliases: ["Amlodipine"], category: "thuốc" },
  { term: "Ringer lactat", category: "dịch truyền" },
  { term: "NaCl 0,9%", category: "dịch truyền" },
  { term: "hồng cầu lắng", category: "chế phẩm máu" },
  { term: "huyết tương tươi đông lạnh", category: "chế phẩm máu" },
  // Thang điểm, phân loại
  { term: "ASA", aliases: ["a ét a"], category: "phân loại" },
  { term: "Mallampati", aliases: ["ma lăm pa ti", "malampati"], category: "thang điểm" },
  { term: "Glasgow", category: "thang điểm" },
  { term: "VAS", category: "thang điểm" },
  { term: "Aldrete", category: "thang điểm" },
  { term: "PARA", category: "sản khoa" },
  // Theo dõi, thông khí, huyết động
  { term: "SpO₂", aliases: ["SpO2", "sờ pê ô hai"], category: "theo dõi" },
  { term: "EtCO₂", aliases: ["EtCO2", "end tidal"], category: "theo dõi" },
  { term: "PEEP", aliases: ["píp", "pip"], category: "thông khí" },
  { term: "Ppeak", category: "thông khí" },
  { term: "Vt (thể tích khí lưu thông)", aliases: ["VT", "tidal volume"], category: "thông khí" },
  { term: "FiO₂", aliases: ["FiO2"], category: "thông khí" },
  { term: "MAP (huyết áp trung bình)", aliases: ["map"], category: "huyết động" },
  { term: "IBP (huyết áp động mạch xâm nhập)", aliases: ["huyết áp xâm lấn"], category: "huyết động" },
  { term: "CVP", category: "huyết động" },
  { term: "SVV", category: "huyết động" },
  { term: "SPV", category: "huyết động" },
  { term: "PPV", category: "huyết động" },
  { term: "GDFT (truyền dịch theo đích)", aliases: ["goal-directed fluid therapy"], category: "hồi sức" },
  { term: "ERAS", aliases: ["e rát", "i rát"], category: "hồi sức" },
  { term: "BIS", category: "theo dõi" },
  { term: "TOF", category: "theo dõi" },
  { term: "PONV", category: "biến chứng" },
  { term: "POVL (mất thị lực sau mổ)", category: "biến chứng" },
  // Thủ thuật, dụng cụ
  { term: "nội khí quản", aliases: ["NKQ"], category: "đường thở" },
  { term: "ống nội khí quản lò xo", category: "đường thở" },
  { term: "mask thanh quản", aliases: ["LMA"], category: "đường thở" },
  { term: "khung Mayfield", aliases: ["mây phiu", "mayfield"], category: "dụng cụ" },
  { term: "catheter tĩnh mạch trung tâm", aliases: ["CVC"], category: "thủ thuật" },
  { term: "gây tê tủy sống", category: "thủ thuật" },
  { term: "gây tê ngoài màng cứng", category: "thủ thuật" },
  { term: "tư thế nằm sấp", category: "tư thế" },
  // Cận lâm sàng
  { term: "Hb", aliases: ["hemoglobin", "huyết sắc tố"], category: "xét nghiệm" },
  { term: "HCT", aliases: ["hematocrit"], category: "xét nghiệm" },
  { term: "PT", category: "xét nghiệm" },
  { term: "APTT", category: "xét nghiệm" },
  { term: "INR", category: "xét nghiệm" },
  { term: "Fibrinogen", category: "xét nghiệm" },
  { term: "SGOT/SGPT", aliases: ["AST/ALT"], category: "xét nghiệm" },
  { term: "Creatinine", aliases: ["creatinin"], category: "xét nghiệm" },
  { term: "Ure", category: "xét nghiệm" },
  { term: "Na⁺", aliases: ["natri"], category: "xét nghiệm" },
  { term: "K⁺", aliases: ["kali"], category: "xét nghiệm" },
  { term: "BMI", category: "chỉ số" },
  // Giải phẫu cột sống
  { term: "L4-L5", aliases: ["L4 L5"], category: "giải phẫu" },
  { term: "L5-S1", aliases: ["L5 S1"], category: "giải phẫu" },
  { term: "tĩnh mạch chủ dưới", category: "giải phẫu" },
  { term: "đám rối thần kinh cánh tay", category: "giải phẫu" },
  // Đơn vị
  { term: "mmHg", category: "đơn vị" },
  { term: "cmH₂O", aliases: ["cmH2O", "xen ti mét nước"], category: "đơn vị" },
  { term: "g/L", category: "đơn vị" },
  { term: "G/L", category: "đơn vị" },
  { term: "mmol/L", category: "đơn vị" },
  { term: "µmol/L", aliases: ["micromol/L"], category: "đơn vị" },
  { term: "ml/kg", category: "đơn vị" },
  // Tổ chức
  { term: "CKI", aliases: ["chuyên khoa một", "chuyên khoa 1"], category: "đào tạo" },
  { term: "CKII", aliases: ["chuyên khoa hai", "chuyên khoa 2"], category: "đào tạo" },
  { term: "bác sĩ nội trú", category: "đào tạo" },
  { term: "Phòng Kế hoạch Tổng hợp", aliases: ["KHTH"], category: "tổ chức" },
];
